### ISSUE TITLE
Register v0.6.0

### ISSUE THREAD

**Issue by maleadt** [FluxML/NNlib.jl#111]
I'd like to release a new version of CuArrays, but that depends on a new version of NNlib.
Would any maintainer here care activating @JuliaRegistrator and cutting a new release?

**Comment by maleadt** [comment]
@MikeInnes @dhairyagandhi96 ping

**Comment by vchuravy** [comment]
@staticfloat @MikeInnes would be great to have a release soon.

**Comment by staticfloat** [comment]
I think we're good to cut a release; @MikeInnes I'm going to release a new version (since Flux/Tracker are already bounded to NNlib 0.5.X) and once this is released/we get a new version of Tracker out in the wild (that isn't bounded to NNlib 0.5.X) we can try and merge https://github.com/FluxML/Flux.jl/pull/718

**Comment by staticfloat** [comment]
@JuliaRegistrator register()
