### ISSUE TITLE
Conv missing negative

### ISSUE THREAD

**Issue by connorpmartin** [FluxML/NNlib.jl#208]
![image](https://user-images.githubusercontent.com/55263157/83975543-75b2df00-a8c2-11ea-94c2-d58bde234c60.png)

I'm really sorry if I'm missing something obvious here, but the result of this convolution appears to be missing a negative. Is conv doing something under the hood that causes this? I've looked at the source and nothing stands out...

**Comment by connorpmartin** [comment]
![image](https://user-images.githubusercontent.com/55263157/83979745-a0ab2c00-a8de-11ea-9f7a-cedaf40c94af.png)
A simpler example. It looks like the filter is being fully reversed before being applied as a convolution.

**Comment by avik-pal** [comment]
IIRC this is the expected behavior from `conv`. The kernels in NNlib are correlation kernels not convolution kernels, so to get the results you mention you need to use `crosscor`. [Here](https://in.mathworks.com/help/images/what-is-image-filtering-in-the-spatial-domain.html) is a bit more detail about crosscor vs conv.
