### ISSUE TITLE
softmax gradients inefficient, API change necessary

### ISSUE THREAD

**Issue by denizyuret** [FluxML/NNlib.jl#248]
The `∇softmax!`, `∇softmax`, `∇logsoftmax!`, `∇logsoftmax` functions recalculate `softmax(x)` which is inefficient (the forward pass already produced the result. I implemented a new api in my [CUDNN PR](https://github.com/denizyuret/CUDA.jl/blob/dy/cudnn/lib/cudnn/nnlib.jl) where these functions get an additional `y` argument with some backward compatible methods with warnings. For backward compatibility you can make this argument optional and default to `y=(log)softmax(x)` but at least we should have the option of passing `y`.

**Comment by CarloLucibello** [comment]
So this is what we need to implement.

**Comment by cossio** [comment]
Why `∇softmax!, ∇softmax, ∇logsoftmax!, ∇logsoftmax` are exported?

**Comment by CarloLucibello** [comment]
∇softmax and others are part of the NNlib's api, there are libraries using them that do not rely on ChainRules or ZygoteRules

**Comment by CarloLucibello** [comment]
actually, I'm not sure if Yota depends on them.

**Comment by CarloLucibello** [comment]
@DhairyaLGandhi ... follow up to discussion in #250 ... 
That we want to pass also the softmax output to the gradient function is quite obvious and is what also the CUDA interface needs
https://github.com/JuliaGPU/CUDA.jl/blob/836de1d298bab4afd41f0a060c1d9c5b07af36a5/lib/cudnn/nnlib.jl#L66

As said in the OP, we basically have 2 options here: 
1. deprecate the version without the output `y`, as currently done in #250 
2. keep supporting it along with the new interface

@DhairyaLGandhi let's make a choice so that I can keep working on #250, I don't want to defer v0.8. 
I vote for option 1, since is what we do for other gradients in this library (e.g. see conv gradients). We can still support  for a while the old API through the deprecations in #250

**Comment by DhairyaLGandhi** [comment]
I would go with 2, considering we will need to iron out the api anyway, and that would have to be updated in cuda.jl as well.

**Comment by CarloLucibello** [comment]
> I would go with 2, considering we will need to iron out the api anyway, and that would have to be updated in cuda.jl as well.

ok

**Comment by denizyuret** [comment]
cuda.jl has already been updated in the dy/cudnn PR where this request
comes from.

**Comment by DhairyaLGandhi** [comment]
Right, but I think we also want to converge on the API for the grad function. currently, we have to do an additional forward pass, whose output we should be able to close over for the gradient. The current form of the gradient API is shadowing CUDNN iiuc?

**Comment by denizyuret** [comment]
Both the old and the new CUDNN interface always required y for the backward
function. I have no idea why it was dropped in NNlib.
